### ISSUE TITLE
Do not depreciate 'getEventObservable

### ISSUE THREAD

**Issue by dotnetdreamer** [paritosh64ce/ngx-pub-sub#4]
Hello,
Thanks for  your wonderful work. I see that you are deprecating the 'getEventObservable'. However, i needed an access to underlying observable since my requirement was to denounce the event. The event i am publishing is from different sources. But i would to subscribe only once in a specific time. Thats why i added a denounce functionality like below:
```

`    this.pubsubSvc.getEventObservable(SyncConstant.EVENT_SYNC_DATA_PUSH_COMPLETE)
      .pipe(debounceTime(300))
      .subscribe(() => {
        if(AppConstant.DEBUG) {
          console.log('ExpenseListingPage:Event received: EVENT_SYNC_DATA_PUSH_COMPLETE');
        }
    });`

```

I would like to know if you remove the **getEventObservable** method, what will be alternative to this ?? Since i dont want my application break after certain time i.e when you remove it...

**Comment by paritosh64ce** [comment]
Got your point. It makes sense. Didn't thought about that scenario earlier. So yes. I will not deprecate that method.

**Comment by dotnetdreamer** [comment]
Yes. Actually i was afraid that you will be removing it and i found also another solution to this problem. but it would be nice to leave your solution as it is. 
Here is what i came up with:
```
    const obv = new Observable(observer => {
      //next will call the observable and pass parameter to subscription
      const callback = (params) => observer.next(params);
      const subc = this.pubsubSvc.subscribe(SyncConstant.EVENT_SYNC_DATA_PUSH_COMPLETE, callback);
      //will be called when unsubscribe calls
      return () => subc.unsubscribe()
    });
    this._syncDataPushCompleteSub = obv.pipe(debounceTime(500))
    .subscribe(() => {
        if(AppConstant.DEBUG) {
          console.log('ExpenseListingPage:Event received: EVENT_SYNC_DATA_PUSH_COMPLETE');
        }
    });
```
