### ISSUE TITLE
Entry point '@pscoped/ngx-pub-sub' contains deep imports into...

### ISSUE THREAD

**Issue by TimoPot** [paritosh64ce/ngx-pub-sub#5]
Entry point '@pscoped/ngx-pub-sub' contains deep imports into
- rxjs/internal/BehaviorSubject
- rxjs/internal/ReplaySubject
- rxjs/internal/Subject
- rxjs/internal/Observable
- rxjs/internal/Subscription
- rxjs/internal/types

This is probably not a problem, but may cause the compilation of entry points to be out of order.

Well in my case it is a problem because I use your ngxPubSub in an Angular library which is used by another Angular App.
That angular App won't build because it complains about missing dependencies, see next error:

An error occurred during the build:
Error: The target entry-point "name of my library" has missing dependencies:
 - rxjs/internal/BehaviorSubject
 - rxjs/internal/ReplaySubject
 - rxjs/internal/Subject
 - rxjs/internal/Observable
 - rxjs/internal/Subscription
 - rxjs/internal/types

**Comment by paritosh64ce** [comment]
I guess it will fix your issue if you install `rxjs` in your Angular App.

**Comment by TimoPot** [comment]
That is not a solution

**Comment by paritosh64ce** [comment]
`Angular` along with `RxJs` are [peerDependencies](https://github.com/paritosh64ce/ngx-pub-sub/blob/master/libs/ngx-pub-sub/package.json#L22) for this library: [RunKit](https://npm.runkit.com/%40pscoped%2Fngx-pub-sub).

**Comment by paritosh64ce** [comment]
`Angular` along with `RxJs` are [peerDependencies](https://github.com/paritosh64ce/ngx-pub-sub/blob/master/libs/ngx-pub-sub/package.json#L22) for this library: [RunKit](https://npm.runkit.com/%40pscoped%2Fngx-pub-sub).

Now if you try to use this package without its dependencies, it's not going to work.

Let me know if you have any confusion.
