### ISSUE TITLE
NgxPubSubModule for angular 14 typescript

### ISSUE THREAD

**Issue by jerrygprakash** [paritosh64ce/ngx-pub-sub#6]
I have implemented  #NgxPubSubModule in my project but it was not accepted by #NgModule imports.

I am getting this error while I import #NgxPubSubModule.

 **#NgxPubSubModule' does not appear to be an #NgModule class.(-996002)

ngx-pub-sub.module.d.ts(1, 22): This likely means that the library (@pscoped/ngx-pub-sub) which declares #NgxPubSubModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also, consider checking with the library's authors to see if the library is expected to be compatible with Ivy.**

What is the solution to this problem

**Comment by paritosh64ce** [comment]
I've published the newer version `5.0.0-beta1`. Although it is compiled with Angular v15 compiler, it should be compatible with v14 as well, as the libraries doesn't have any component templates.

Let me know if it works, I'll publish it as a stable release.

**Comment by NRV90** [comment]
Hi,

Thanks for taking time to look into this. I am running into the following issue after updating to the beta version.

npm ERR! Found: @angular/common@14.2.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"14.2.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0" from @pscoped/ngx-pub-sub@5.0.0-beta1
npm ERR! node_modules/@pscoped/ngx-pub-sub
npm ERR!   @pscoped/ngx-pub-sub@"^5.0.0-beta1" from the root project

Thanks!

**Comment by paritosh64ce** [comment]
Hi there! Published another beta: `5.0.0-beta2`.

Although I am not sure why it was giving that error, I've removed `peerDependencies` of `@angular/common` and `@angular/core`. It should not give you error; at-least for `npm install`.

Give it a try, will publish a stable release if it works for you.

**Comment by paritosh64ce** [comment]
Published `@pscoped/ngx-pub-sub` `5.0.0`, compatible with `@angular` v13+
